[rospy.client][INFO] 2020-09-10 11:58:41,235: init_node, name[/rotate_in_place], pid[18045]
[xmlrpc][INFO] 2020-09-10 11:58:41,236: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-10 11:58:41,236: Started XML-RPC server [http://cuboid0009:40319/]
[rospy.init][INFO] 2020-09-10 11:58:41,237: ROS Slave URI: [http://cuboid0009:40319/]
[rospy.impl.masterslave][INFO] 2020-09-10 11:58:41,237: _ready: http://cuboid0009:40319/
[rospy.registration][INFO] 2020-09-10 11:58:41,238: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-09-10 11:58:41,238: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-10 11:58:41,337: registered with master
[rospy.rosout][INFO] 2020-09-10 11:58:41,338: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-10 11:58:41,340: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-10 11:58:41,341: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2020-09-10 11:58:41,346: Init robot_pose subscriber
[rosout][INFO] 2020-09-10 11:58:41,348: Init global path subscriber
[rosout][INFO] 2020-09-10 11:58:41,351: Init local costmap subscriber
[rosout][INFO] 2020-09-10 11:58:41,353: Init move_base result subscriber
[rospy.internal][INFO] 2020-09-10 11:58:41,354: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:40091/], count 0
[rosout][INFO] 2020-09-10 11:58:41,356: Init move_base feedback subscriber
[rospy.internal][INFO] 2020-09-10 11:58:41,358: topic[/move_base/result] adding connection to [http://cuboid0009:40091/], count 0
[rosout][INFO] 2020-09-10 11:58:41,358: [RotateInPlace] Init publisher and subscriber
[rospy.internal][INFO] 2020-09-10 11:58:41,360: topic[/move_base/feedback] adding connection to [http://cuboid0009:40091/], count 0
[rospy.internal][INFO] 2020-09-10 11:58:41,361: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:40091/], count 0
[rospy.internal][INFO] 2020-09-10 11:58:41,362: topic[/robot_pose] adding connection to [http://cuboid0009:38391/], count 0
[rospy.internal][INFO] 2020-09-10 11:58:41,577: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-10 11:58:41,579: topic[/rotate_vel] adding connection to [/twist_mux], count 0
[rosout][INFO] 2020-09-10 11:59:15,088: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 11:59:18,320: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 12:00:31,429: Unknown error initiating TCP/IP socket to cuboid0009:52119 (http://cuboid0009:40091/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:00:31,430: topic[/move_base/feedback] removing connection to http://cuboid0009:40091/
[rospy.internal][WARNING] 2020-09-10 12:00:31,430: Unknown error initiating TCP/IP socket to cuboid0009:52119 (http://cuboid0009:40091/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:00:31,431: topic[/move_base/result] removing connection to http://cuboid0009:40091/
[rospy.internal][WARNING] 2020-09-10 12:00:31,431: Unknown error initiating TCP/IP socket to cuboid0009:52119 (http://cuboid0009:40091/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:00:31,431: Unknown error initiating TCP/IP socket to cuboid0009:52119 (http://cuboid0009:40091/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:00:31,431: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:40091/
[rospy.internal][INFO] 2020-09-10 12:00:31,431: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:40091/
[rospy.internal][INFO] 2020-09-10 12:00:33,588: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:45177/], count 0
[rospy.internal][INFO] 2020-09-10 12:00:34,003: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:45177/], count 0
[rospy.internal][INFO] 2020-09-10 12:00:34,268: topic[/move_base/result] adding connection to [http://cuboid0009:45177/], count 0
[rospy.internal][INFO] 2020-09-10 12:00:34,272: topic[/move_base/feedback] adding connection to [http://cuboid0009:45177/], count 0
[rosout][INFO] 2020-09-10 12:01:17,391: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:01:21,046: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:04:17,399: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:04:22,667: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:06:46,153: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 12:06:46,154: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  84
[rosout][INFO] 2020-09-10 12:06:50,681: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 12:06:50,683: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  84
[rospy.internal][WARNING] 2020-09-10 12:06:53,933: Unknown error initiating TCP/IP socket to cuboid0009:57491 (http://cuboid0009:45177/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-09-10 12:06:53,933: Unknown error initiating TCP/IP socket to cuboid0009:57491 (http://cuboid0009:45177/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:06:53,933: Unknown error initiating TCP/IP socket to cuboid0009:57491 (http://cuboid0009:45177/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:06:53,934: Unknown error initiating TCP/IP socket to cuboid0009:57491 (http://cuboid0009:45177/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:06:53,934: topic[/move_base/feedback] removing connection to http://cuboid0009:45177/
[rospy.internal][INFO] 2020-09-10 12:06:53,934: topic[/move_base/result] removing connection to http://cuboid0009:45177/
[rospy.internal][INFO] 2020-09-10 12:06:53,934: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:45177/
[rospy.internal][INFO] 2020-09-10 12:06:53,934: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:45177/
[rospy.internal][INFO] 2020-09-10 12:06:56,155: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:38141/], count 0
[rospy.internal][INFO] 2020-09-10 12:06:56,521: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:38141/], count 0
[rospy.internal][INFO] 2020-09-10 12:06:56,836: topic[/move_base/feedback] adding connection to [http://cuboid0009:38141/], count 0
[rospy.internal][INFO] 2020-09-10 12:06:56,837: topic[/move_base/result] adding connection to [http://cuboid0009:38141/], count 0
[rosout][INFO] 2020-09-10 12:07:03,638: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:07:06,672: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 12:07:12,675: Unknown error initiating TCP/IP socket to cuboid0009:49053 (http://cuboid0009:38141/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-09-10 12:07:12,675: Unknown error initiating TCP/IP socket to cuboid0009:49053 (http://cuboid0009:38141/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:07:12,675: Unknown error initiating TCP/IP socket to cuboid0009:49053 (http://cuboid0009:38141/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:07:12,675: Unknown error initiating TCP/IP socket to cuboid0009:49053 (http://cuboid0009:38141/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:07:12,676: topic[/move_base/result] removing connection to http://cuboid0009:38141/
[rospy.internal][INFO] 2020-09-10 12:07:12,676: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:38141/
[rospy.internal][INFO] 2020-09-10 12:07:12,676: topic[/move_base/feedback] removing connection to http://cuboid0009:38141/
[rospy.internal][INFO] 2020-09-10 12:07:12,676: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:38141/
[rospy.internal][INFO] 2020-09-10 12:07:14,812: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:42465/], count 0
[rospy.internal][INFO] 2020-09-10 12:07:15,227: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:42465/], count 0
[rospy.internal][INFO] 2020-09-10 12:07:15,493: topic[/move_base/feedback] adding connection to [http://cuboid0009:42465/], count 0
[rospy.internal][INFO] 2020-09-10 12:07:15,493: topic[/move_base/result] adding connection to [http://cuboid0009:42465/], count 0
[rosout][INFO] 2020-09-10 12:07:35,604: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:07:38,442: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 12:08:54,373: Unknown error initiating TCP/IP socket to cuboid0009:57301 (http://cuboid0009:42465/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:08:54,373: topic[/move_base/result] removing connection to http://cuboid0009:42465/
[rospy.internal][WARNING] 2020-09-10 12:08:54,373: Unknown error initiating TCP/IP socket to cuboid0009:57301 (http://cuboid0009:42465/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:08:54,374: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:42465/
[rospy.internal][WARNING] 2020-09-10 12:08:54,374: Unknown error initiating TCP/IP socket to cuboid0009:57301 (http://cuboid0009:42465/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:08:54,374: topic[/move_base/feedback] removing connection to http://cuboid0009:42465/
[rospy.internal][WARNING] 2020-09-10 12:08:54,374: Unknown error initiating TCP/IP socket to cuboid0009:57301 (http://cuboid0009:42465/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:08:54,374: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:42465/
[rospy.internal][INFO] 2020-09-10 12:08:56,556: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:41937/], count 0
[rospy.internal][INFO] 2020-09-10 12:08:56,972: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:41937/], count 0
[rospy.internal][INFO] 2020-09-10 12:08:57,288: topic[/move_base/result] adding connection to [http://cuboid0009:41937/], count 0
[rospy.internal][INFO] 2020-09-10 12:08:57,289: topic[/move_base/feedback] adding connection to [http://cuboid0009:41937/], count 0
[rosout][INFO] 2020-09-10 12:10:10,944: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:10:13,570: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:12:00,935: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:12:04,774: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:12:07,489: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:12:07,489: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:12:31,625: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:12:34,461: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:13:22,702: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:13:25,534: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:13:39,092: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:13:44,140: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:14:16,076: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:14:20,121: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:16:33,672: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:16:33,672: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:16:36,384: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:16:40,643: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:17:49,677: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:17:50,891: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 12:17:53,886: Unknown error initiating TCP/IP socket to cuboid0009:54827 (http://cuboid0009:41937/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:17:53,886: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:41937/
[rospy.internal][WARNING] 2020-09-10 12:17:53,887: Unknown error initiating TCP/IP socket to cuboid0009:54827 (http://cuboid0009:41937/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-09-10 12:17:53,887: Unknown error initiating TCP/IP socket to cuboid0009:54827 (http://cuboid0009:41937/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:17:53,887: Unknown error initiating TCP/IP socket to cuboid0009:54827 (http://cuboid0009:41937/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:17:53,887: topic[/move_base/result] removing connection to http://cuboid0009:41937/
[rospy.internal][INFO] 2020-09-10 12:17:53,887: topic[/move_base/feedback] removing connection to http://cuboid0009:41937/
[rospy.internal][INFO] 2020-09-10 12:17:53,887: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:41937/
[rospy.internal][INFO] 2020-09-10 12:17:56,187: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:35977/], count 0
[rospy.internal][INFO] 2020-09-10 12:17:56,502: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:35977/], count 0
[rospy.internal][INFO] 2020-09-10 12:17:56,917: topic[/move_base/feedback] adding connection to [http://cuboid0009:35977/], count 0
[rospy.internal][INFO] 2020-09-10 12:17:56,918: topic[/move_base/result] adding connection to [http://cuboid0009:35977/], count 0
[rospy.internal][WARNING] 2020-09-10 12:18:02,421: Unknown error initiating TCP/IP socket to cuboid0009:49767 (http://cuboid0009:35977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:18:02,421: topic[/move_base/feedback] removing connection to http://cuboid0009:35977/
[rospy.internal][WARNING] 2020-09-10 12:18:02,422: Unknown error initiating TCP/IP socket to cuboid0009:49767 (http://cuboid0009:35977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:18:02,422: topic[/move_base/result] removing connection to http://cuboid0009:35977/
[rospy.internal][WARNING] 2020-09-10 12:18:02,422: Unknown error initiating TCP/IP socket to cuboid0009:49767 (http://cuboid0009:35977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:18:02,422: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:35977/
[rospy.internal][WARNING] 2020-09-10 12:18:03,430: Unknown error initiating TCP/IP socket to cuboid0009:49767 (http://cuboid0009:35977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:18:03,430: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:35977/
[rospy.internal][INFO] 2020-09-10 12:18:04,638: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:45997/], count 0
[rospy.internal][INFO] 2020-09-10 12:18:04,953: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:45997/], count 0
[rospy.internal][INFO] 2020-09-10 12:18:05,268: topic[/move_base/feedback] adding connection to [http://cuboid0009:45997/], count 0
[rospy.internal][INFO] 2020-09-10 12:18:05,269: topic[/move_base/result] adding connection to [http://cuboid0009:45997/], count 0
[rosout][INFO] 2020-09-10 12:19:52,043: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:19:53,460: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:21:32,627: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:21:36,877: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:21:39,595: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:21:44,258: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 12:22:31,259: Unknown error initiating TCP/IP socket to cuboid0009:50183 (http://cuboid0009:45997/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:22:31,259: topic[/move_base/feedback] removing connection to http://cuboid0009:45997/
[rospy.internal][WARNING] 2020-09-10 12:22:31,260: Unknown error initiating TCP/IP socket to cuboid0009:50183 (http://cuboid0009:45997/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:22:31,260: topic[/move_base/result] removing connection to http://cuboid0009:45997/
[rospy.internal][WARNING] 2020-09-10 12:22:31,260: Unknown error initiating TCP/IP socket to cuboid0009:50183 (http://cuboid0009:45997/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:22:31,260: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:45997/
[rospy.internal][WARNING] 2020-09-10 12:22:31,260: Unknown error initiating TCP/IP socket to cuboid0009:50183 (http://cuboid0009:45997/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:22:31,261: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:45997/
[rospy.internal][INFO] 2020-09-10 12:22:33,407: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:35527/], count 0
[rospy.internal][INFO] 2020-09-10 12:22:33,773: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:35527/], count 0
[rospy.internal][INFO] 2020-09-10 12:22:34,088: topic[/move_base/feedback] adding connection to [http://cuboid0009:35527/], count 0
[rospy.internal][INFO] 2020-09-10 12:22:34,089: topic[/move_base/result] adding connection to [http://cuboid0009:35527/], count 0
[rosout][INFO] 2020-09-10 12:22:56,611: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:23:01,671: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:24:59,905: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:25:05,971: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:26:46,929: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:26:52,183: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:28:41,574: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:28:41,574: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:28:42,481: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:28:45,915: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:29:48,916: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:29:53,566: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:31:54,117: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:31:57,552: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:33:25,255: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:33:30,107: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:34:14,135: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:34:14,136: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:34:14,748: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:34:17,780: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:36:29,835: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:36:32,871: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:37:04,533: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:37:10,193: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 12:38:06,880: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:38:06,880: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:38:07,486: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:38:10,321: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 12:39:28,882: Unknown error initiating TCP/IP socket to cuboid0009:42407 (http://cuboid0009:35527/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 12:39:28,883: topic[/move_base/feedback] removing connection to http://cuboid0009:35527/
[rospy.internal][WARNING] 2020-09-10 12:39:28,883: Unknown error initiating TCP/IP socket to cuboid0009:42407 (http://cuboid0009:35527/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:39:28,883: Unknown error initiating TCP/IP socket to cuboid0009:42407 (http://cuboid0009:35527/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 12:39:28,883: Unknown error initiating TCP/IP socket to cuboid0009:42407 (http://cuboid0009:35527/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 12:39:28,883: topic[/move_base/result] removing connection to http://cuboid0009:35527/
[rospy.internal][INFO] 2020-09-10 12:39:28,883: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:35527/
[rospy.internal][INFO] 2020-09-10 12:39:28,883: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:35527/
[rospy.internal][INFO] 2020-09-10 12:39:31,040: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:34101/], count 0
[rospy.internal][INFO] 2020-09-10 12:39:31,354: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:34101/], count 0
[rospy.internal][INFO] 2020-09-10 12:39:31,620: topic[/move_base/result] adding connection to [http://cuboid0009:34101/], count 0
[rospy.internal][INFO] 2020-09-10 12:39:31,620: topic[/move_base/feedback] adding connection to [http://cuboid0009:34101/], count 0
[rosout][INFO] 2020-09-10 12:39:38,605: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:39:40,030: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:39:42,743: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 12:39:42,743: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 12:40:22,250: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 12:40:27,705: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:22:57,987: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:23:02,655: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:24:30,069: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:24:30,071: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  88
[rosout][INFO] 2020-09-10 13:24:33,994: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:24:33,997: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  99
[rosout][INFO] 2020-09-10 13:25:25,280: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:25:28,715: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:25:37,163: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:25:37,164: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  86
[rosout][INFO] 2020-09-10 13:25:52,256: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:25:52,459: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:25:56,373: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:25:56,373: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:25:57,582: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:26:01,236: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:26:34,998: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:26:39,256: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:28:02,160: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:28:07,440: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:28:14,071: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:28:19,733: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:31:20,009: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:31:20,010: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:31:22,724: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:31:28,999: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:31:34,426: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:31:48,581: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:33:09,385: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:33:12,636: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:33:14,446: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:33:17,278: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:34:14,876: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:34:14,878: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  99
[rospy.internal][WARNING] 2020-09-10 13:34:17,934: Unknown error initiating TCP/IP socket to cuboid0009:40667 (http://cuboid0009:34101/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 13:34:17,935: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:34101/
[rospy.internal][WARNING] 2020-09-10 13:34:17,935: Unknown error initiating TCP/IP socket to cuboid0009:40667 (http://cuboid0009:34101/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 13:34:17,935: Unknown error initiating TCP/IP socket to cuboid0009:40667 (http://cuboid0009:34101/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 13:34:17,935: Unknown error initiating TCP/IP socket to cuboid0009:40667 (http://cuboid0009:34101/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:34:17,936: topic[/move_base/feedback] removing connection to http://cuboid0009:34101/
[rospy.internal][INFO] 2020-09-10 13:34:17,936: topic[/move_base/result] removing connection to http://cuboid0009:34101/
[rospy.internal][INFO] 2020-09-10 13:34:17,936: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:34101/
[rospy.internal][INFO] 2020-09-10 13:34:20,409: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:37387/], count 0
[rospy.internal][INFO] 2020-09-10 13:34:20,724: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:37387/], count 0
[rospy.internal][INFO] 2020-09-10 13:34:21,039: topic[/move_base/feedback] adding connection to [http://cuboid0009:37387/], count 0
[rospy.internal][INFO] 2020-09-10 13:34:21,040: topic[/move_base/result] adding connection to [http://cuboid0009:37387/], count 0
[rosout][INFO] 2020-09-10 13:35:34,773: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:35:34,773: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:35:35,979: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:35:43,875: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:35:49,608: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:35:50,624: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  88
[rospy.internal][WARNING] 2020-09-10 13:35:51,651: Unknown error initiating TCP/IP socket to cuboid0009:51831 (http://cuboid0009:37387/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:35:51,651: topic[/move_base/feedback] removing connection to http://cuboid0009:37387/
[rospy.internal][WARNING] 2020-09-10 13:35:51,652: Unknown error initiating TCP/IP socket to cuboid0009:51831 (http://cuboid0009:37387/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-09-10 13:35:51,652: Unknown error initiating TCP/IP socket to cuboid0009:51831 (http://cuboid0009:37387/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:35:51,652: topic[/move_base/result] removing connection to http://cuboid0009:37387/
[rospy.internal][WARNING] 2020-09-10 13:35:51,652: Unknown error initiating TCP/IP socket to cuboid0009:51831 (http://cuboid0009:37387/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:35:51,653: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:37387/
[rospy.internal][INFO] 2020-09-10 13:35:51,653: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:37387/
[rospy.internal][INFO] 2020-09-10 13:35:53,854: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:45829/], count 0
[rospy.internal][INFO] 2020-09-10 13:35:54,269: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:45829/], count 0
[rospy.internal][INFO] 2020-09-10 13:35:54,485: topic[/move_base/feedback] adding connection to [http://cuboid0009:45829/], count 0
[rospy.internal][INFO] 2020-09-10 13:35:54,485: topic[/move_base/result] adding connection to [http://cuboid0009:45829/], count 0
[rosout][INFO] 2020-09-10 13:35:59,068: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:35:59,685: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  92
[rosout][INFO] 2020-09-10 13:36:02,700: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:36:02,701: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  92
[rosout][INFO] 2020-09-10 13:36:06,617: [RotateInPlace] Rotate here.
[rosout][ERROR] 2020-09-10 13:36:06,618: [RotateInPlace] cannot rotate in place becase there is a potential collision. Cost:  84
[rosout][INFO] 2020-09-10 13:36:10,840: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:36:15,696: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:36:19,918: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:36:23,555: [RotateInPlace] move_base task is cancelled.
[rosout][INFO] 2020-09-10 13:36:33,792: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:36:39,063: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:37:31,840: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:37:35,281: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:38:10,269: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:38:14,920: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:38:41,746: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:38:44,980: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:40:48,849: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:40:54,716: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:41:58,653: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:42:02,695: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:42:08,132: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:42:13,385: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:44:32,002: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:44:34,854: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:44:55,364: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:44:58,820: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:47:56,337: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:48:00,177: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:48:28,829: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:48:31,665: [RotateInPlace] Rotated.
[rosout][INFO] 2020-09-10 13:51:07,505: [RotateInPlace] Rotate here.
[rosout][INFO] 2020-09-10 13:51:11,147: [RotateInPlace] Rotated.
[rospy.internal][WARNING] 2020-09-10 13:51:44,086: Unknown error initiating TCP/IP socket to cuboid0009:39275 (http://cuboid0009:45829/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 13:51:44,086: topic[/move_base/result] removing connection to http://cuboid0009:45829/
[rospy.internal][WARNING] 2020-09-10 13:51:44,086: Unknown error initiating TCP/IP socket to cuboid0009:39275 (http://cuboid0009:45829/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:51:44,086: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:45829/
[rospy.internal][WARNING] 2020-09-10 13:51:44,087: Unknown error initiating TCP/IP socket to cuboid0009:39275 (http://cuboid0009:45829/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-09-10 13:51:44,087: topic[/move_base/feedback] removing connection to http://cuboid0009:45829/
[rospy.internal][WARNING] 2020-09-10 13:51:44,087: Unknown error initiating TCP/IP socket to cuboid0009:39275 (http://cuboid0009:45829/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:51:44,087: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:45829/
[rospy.internal][INFO] 2020-09-10 13:51:46,343: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:35745/], count 0
[rospy.internal][INFO] 2020-09-10 13:51:46,758: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:35745/], count 0
[rospy.internal][INFO] 2020-09-10 13:51:46,974: topic[/move_base/feedback] adding connection to [http://cuboid0009:35745/], count 0
[rospy.internal][INFO] 2020-09-10 13:51:46,975: topic[/move_base/result] adding connection to [http://cuboid0009:35745/], count 0
[rospy.internal][WARNING] 2020-09-10 13:52:41,228: Unknown error initiating TCP/IP socket to cuboid0009:39825 (http://cuboid0009:35745/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-09-10 13:52:41,228: Unknown error initiating TCP/IP socket to cuboid0009:39825 (http://cuboid0009:35745/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2020-09-10 13:52:41,228: Unknown error initiating TCP/IP socket to cuboid0009:39825 (http://cuboid0009:35745/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:52:41,229: topic[/move_base/result] removing connection to http://cuboid0009:35745/
[rospy.internal][INFO] 2020-09-10 13:52:41,229: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:35745/
[rospy.internal][INFO] 2020-09-10 13:52:41,229: topic[/move_base/feedback] removing connection to http://cuboid0009:35745/
[rospy.internal][WARNING] 2020-09-10 13:52:41,229: Unknown error initiating TCP/IP socket to cuboid0009:39825 (http://cuboid0009:35745/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-09-10 13:52:41,230: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:35745/
[rospy.internal][INFO] 2020-09-10 13:52:43,323: topic[/move_base/NavfnROS/plan] adding connection to [http://cuboid0009:38215/], count 0
[rospy.internal][INFO] 2020-09-10 13:52:43,638: topic[/move_base/local_costmap/costmap_updates] adding connection to [http://cuboid0009:38215/], count 0
[rospy.internal][INFO] 2020-09-10 13:52:43,853: topic[/move_base/feedback] adding connection to [http://cuboid0009:38215/], count 0
[rospy.internal][INFO] 2020-09-10 13:52:43,854: topic[/move_base/result] adding connection to [http://cuboid0009:38215/], count 0
[rosout][INFO] 2020-09-10 13:52:49,712: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:53:20,658: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:53:21,564: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:53:21,565: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:53:24,577: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:53:55,723: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:53:56,631: [RotateInPlace] Rotate here.
[rosout][WARNING] 2020-09-10 13:53:56,632: [RotateInPlace] Feedback is stopped.
[rosout][INFO] 2020-09-10 13:54:02,668: [RotateInPlace] Rotate here.
[rospy.core][INFO] 2020-09-10 13:54:10,303: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-09-10 13:54:10,307: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-10 13:54:10,308: topic[/rotate_vel] removing connection to /twist_mux
[rospy.internal][INFO] 2020-09-10 13:54:10,308: topic[/move_base/NavfnROS/plan] removing connection to http://cuboid0009:38215/
[rospy.internal][WARNING] 2020-09-10 13:54:10,308: Unknown error initiating TCP/IP socket to cuboid0009:33763 (http://cuboid0009:38215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-09-10 13:54:10,309: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2020-09-10 13:54:10,309: topic[/move_base/result] removing connection to http://cuboid0009:38215/
[rospy.internal][INFO] 2020-09-10 13:54:10,309: topic[/move_base/feedback] removing connection to http://cuboid0009:38215/
[rospy.internal][INFO] 2020-09-10 13:54:10,309: topic[/robot_pose] removing connection to http://cuboid0009:38391/
[rospy.internal][INFO] 2020-09-10 13:54:10,310: topic[/move_base/local_costmap/costmap_updates] removing connection to http://cuboid0009:38215/
[rospy.impl.masterslave][INFO] 2020-09-10 13:54:10,310: signal-2
[rosout][WARNING] 2020-09-10 13:54:11,428: [RotateInPlace] Feedback is stopped.
[rospy.core][INFO] 2020-09-10 13:54:11,730: signal_shutdown [atexit]
